name: Build and publish container image

on:
  push:
    branches:
      - main

env:
  TAG_NAME: gcp-deploy-test:${{ github.sha }}
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/gcp-deploy-test:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}
